import type {
  PIDEquipment,
  PIDLine,
  PIDDocument,
  PIDAreaNode,
} from './types'

export const initialEquipments: PIDEquipment[] = [
  {
    id: 'P-101AB',
    tag: 'P-101 A/B',
    name: 'Crude Feed Pump',
    type: 'Centrifugal Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description:
      'Main crude feed pump used to charge crude oil to the preheat train. Two units (A/B) with one in service and one standby.',
    specs: {
      Capacity: '450 m³/h',
      Head: '120 m',
      Power: '250 kW',
      RPM: '2950 RPM',
      Fluid: 'Desalted Crude',
      Temperature: '85 °C',
    },
    connectedLines: ['10"-CR-101', '10"-CR-102'],
    documents: ['DOC-001.pdf', 'DOC-010.pdf', 'DOC-012.pdf'],
  },
  {
    id: 'P-101A',
    tag: 'P-101 A',
    name: 'Crude Feed Pump A',
    type: 'Centrifugal Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Duty pump for primary crude oil transfer to preheat exchanger train E-101.',
    specs: { Flow: '450 m³/h', Motor: '250 kW Elec' },
  },
  {
    id: 'P-101B',
    tag: 'P-101 B',
    name: 'Crude Feed Pump B',
    type: 'Centrifugal Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'Standby',
    description: 'Auto-kickin standby pump for crude feed service.',
    specs: { Flow: '450 m³/h', Motor: '250 kW Elec' },
  },
  {
    id: 'E-101',
    tag: 'E-101',
    name: 'Crude Preheater 1',
    type: 'Heat Exchanger',
    service: 'Crude Preheat',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'First-stage shell and tube heat exchanger preheating crude using residue heat stream.',
    specs: { Duty: '14.5 MW', Area: '620 m²', ShellP: '18 bar' },
  },
  {
    id: 'E-102',
    tag: 'E-102',
    name: 'Crude Preheater 2',
    type: 'Heat Exchanger',
    service: 'Crude Preheat',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Second-stage heat exchanger prior to desalter feed stage.',
    specs: { Duty: '12.8 MW', Area: '580 m²' },
  },
  {
    id: 'E-103',
    tag: 'E-103',
    name: 'Crude Preheater 3',
    type: 'Heat Exchanger',
    service: 'Crude Preheat',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'High-temperature preheat exchangers before fired heater inlet.',
    specs: { Duty: '16.2 MW', Area: '710 m²' },
  },
  {
    id: 'T-101',
    tag: 'T-101',
    name: 'Crude Distillation Column',
    type: 'Distillation Column',
    service: 'Main Fractionation',
    unit: 'CDU-03',
    area: '200 - Crude Column',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Atmospheric crude distillation column separating crude oil into LPG, naphtha, kerosene, diesel, and atmospheric residue.',
    specs: { Height: '48 m', Diameter: '4.2 m', Trays: '42 Valve Trays' },
  },
  {
    id: 'E-201',
    tag: 'E-201',
    name: 'Reboiler Exchanger',
    type: 'Heat Exchanger',
    service: 'Column Reboil',
    unit: 'CDU-03',
    area: '200 - Crude Column',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Thermosiphon reboiler supplying heat duty to column bottom section.',
  },
  {
    id: 'V-201',
    tag: 'V-201',
    name: 'Reflux Drum',
    type: 'Pressure Vessel',
    service: 'Overhead Separator',
    unit: 'CDU-03',
    area: '300 - Overhead',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Overhead condensed vapor separator collecting light naphtha condensate and sour water.',
  },
  {
    id: 'E-301',
    tag: 'E-301',
    name: 'Overhead Condenser',
    type: 'Heat Exchanger',
    service: 'Vapor Condensing',
    unit: 'CDU-03',
    area: '300 - Overhead',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Fin-fan air cooler condensing column overhead vapors before reflux drum.',
  },
]

export const initialLines: PIDLine[] = [
  {
    id: 'L-101',
    lineNo: '10"-CR-101',
    service: 'Crude Feed',
    from: 'Tank-01',
    to: 'P-101 A/B',
    size: '10 Inch',
    spec: 'A1A-CS',
  },
  {
    id: 'L-102',
    lineNo: '10"-CR-102',
    service: 'Crude Feed',
    from: 'P-101 A/B',
    to: 'E-101',
    size: '10 Inch',
    spec: 'A1A-CS',
  },
  {
    id: 'L-103',
    lineNo: '8"-CR-103',
    service: 'Crude Feed',
    from: 'E-101',
    to: 'E-102',
    size: '8 Inch',
    spec: 'A1A-CS',
  },
  {
    id: 'L-104',
    lineNo: '8"-CR-104',
    service: 'Crude Feed',
    from: 'E-102',
    to: 'T-101',
    size: '8 Inch',
    spec: 'A1A-CS',
  },
]

/**
 * Connected documents anchored in the real refinery corpus (manifest/documents.json).
 * DOC-012 is a TRAINING symbols reference, labeled as such — not an as-built drawing.
 */
export const initialDocuments: PIDDocument[] = [
  {
    id: 'DOC-001',
    fileName: 'DOC-001.pdf',
    title: 'OISD Case Study: Fire Incident in Crude and Vacuum Distillation Unit (CDU/VDU)',
    type: 'Inspection',
    date: '2026-06-01',
    fileSize: '1.2 MB',
    tagRef: 'CDU-03',
  },
  {
    id: 'DOC-007',
    fileName: 'DOC-007.pdf',
    title: 'CSB Report: Chevron Richmond Refinery #4 Crude Unit pipe rupture and fire',
    type: 'Inspection',
    date: '2015-01-28',
    fileSize: '7.7 MB',
    tagRef: 'T-101',
  },
  {
    id: 'DOC-008',
    fileName: 'DOC-008.pdf',
    title: 'CSB Report: Tesoro Anacortes Refinery heat exchanger rupture',
    type: 'Inspection',
    date: '2014-05-01',
    fileSize: '6.3 MB',
    tagRef: 'E-101',
  },
  {
    id: 'DOC-010',
    fileName: 'DOC-010.pdf',
    title: 'MRPL Specification for Motor Gasoline BS-IV (IS 2796:2008 Amd.1, MG 91)',
    type: 'Datasheet',
    date: '—',
    fileSize: '27 KB',
    tagRef: 'CDU-03',
  },
  {
    id: 'DOC-012',
    fileName: 'DOC-012.pdf',
    title: 'Industrial Instrumentation Ch.7: P&ID symbols, tags and loops (TRAINING)',
    type: 'Reference',
    date: '2019-01-04',
    fileSize: '62.1 MB',
    tagRef: 'CDU-03',
  },
]

export const areaNodes: PIDAreaNode[] = [
  {
    id: 'area-100',
    name: 'Area 100 - Crude Preheat',
    code: '100',
    categories: [
      { id: 'cat-exchangers-100', name: 'Heat Exchangers', items: ['E-101', 'E-102', 'E-103'] },
      { id: 'cat-pumps-100', name: 'Pumps', items: ['P-101AB', 'P-101A', 'P-101B'] },
      { id: 'cat-valves-100', name: 'Valves', items: ['VLV-101', 'VLV-102'] },
      { id: 'cat-inst-100', name: 'Instruments', items: ['FIT-101', 'PIT-101'] },
    ],
  },
  {
    id: 'area-200',
    name: 'Area 200 - Crude Column',
    code: '200',
    categories: [
      { id: 'cat-columns-200', name: 'Columns', items: ['T-101'] },
      { id: 'cat-exchangers-200', name: 'Heat Exchangers', items: ['E-201'] },
      { id: 'cat-valves-200', name: 'Valves', items: ['VLV-201'] },
      { id: 'cat-inst-200', name: 'Instruments', items: ['TIT-201', 'LIC-201'] },
    ],
  },
  {
    id: 'area-300',
    name: 'Area 300 - Overhead',
    code: '300',
    categories: [
      { id: 'cat-exchangers-300', name: 'Condenser', items: ['E-301'] },
      { id: 'cat-vessels-300', name: 'Reflux Drum', items: ['V-201'] },
      { id: 'cat-inst-300', name: 'Instruments', items: ['PIC-301', 'FI-301'] },
    ],
  },
]
