/**
 * Mock data for HYPERION Screen 4 & 5 — Investigations & Investigation Analysis Workspaces.
 * Models representative engineering investigations, telemetry trend metrics,
 * evidence records, similar equipment benchmarks, and contextual AI actions.
 * @module @deepseek-ai/dsh-client-ui-conversation/client/investigations/mockData
 */

import type {
  InvestigationAnalysisDetailData,
  InvestigationsWorkspaceData,
} from './types.ts'

export const DEFAULT_INVESTIGATIONS_DATA: InvestigationsWorkspaceData = {
  breadcrumb: ['Investigations', 'All Investigations'],
  title: 'Investigations',
  subtitle: 'Track, analyze and resolve plant issues with AI assistance.',

  counts: {
    open: 7,
    inProgress: 3,
    resolved: 12,
    onHold: 2,
  },

  investigations: [
    {
      id: 'inv-001',
      code: '#INV-2024-001',
      tag: 'P-204',
      equipmentType: 'pump',
      severity: 'high',
      title: 'High vibration in Crude Feed Pump',
      plantMetadata: 'CDU-03 · Equipment · Vibration',
      updatedTimeAgo: 'Updated 2 hours ago',
      status: 'open',
      statusLabel: 'Open',
      assignee: { initial: 'N', name: 'Narendar', color: 'blue' },
    },
    {
      id: 'inv-002',
      code: '#INV-2024-002',
      tag: 'E-101',
      equipmentType: 'exchanger',
      severity: 'medium',
      title: 'Tube leak suspicion in Crude Preheater',
      plantMetadata: 'CDU-03 · Heat Exchanger · Leak',
      updatedTimeAgo: 'Updated 1 day ago',
      status: 'in-progress',
      statusLabel: 'In Progress',
      assignee: { initial: 'R', name: 'Rahul', color: 'purple' },
    },
    {
      id: 'inv-003',
      code: '#INV-2024-003',
      tag: 'V-201',
      equipmentType: 'vessel',
      severity: 'medium',
      title: 'Abnormal temperature in Reflux Drum',
      plantMetadata: 'CDU-03 · Vessel · Temperature',
      updatedTimeAgo: 'Updated 2 days ago',
      status: 'open',
      statusLabel: 'Open',
      assignee: { initial: 'S', name: 'Sanjay', color: 'orange' },
    },
    {
      id: 'inv-004',
      code: '#INV-2024-004',
      tag: 'H-301',
      equipmentType: 'reactor',
      severity: 'low',
      title: 'Efficiency drop in Hydrocracker',
      plantMetadata: 'HCU-01 · Reactor · Performance',
      updatedTimeAgo: 'Updated 3 days ago',
      status: 'in-progress',
      statusLabel: 'In Progress',
      assignee: { initial: 'N', name: 'Narendar', color: 'orange' },
    },
    {
      id: 'inv-005',
      code: '#INV-2024-005',
      tag: 'P-101 A/B',
      equipmentType: 'pump',
      severity: 'high',
      title: 'Frequent trip in Feed Pump A/B',
      plantMetadata: 'CDU-03 · Pump · Trip',
      updatedTimeAgo: 'Updated 4 days ago',
      status: 'on-hold',
      statusLabel: 'On Hold',
      assignee: { initial: 'R', name: 'Rahul', color: 'blue' },
    },
    {
      id: 'inv-006',
      code: '#INV-2024-006',
      tag: 'T-101',
      equipmentType: 'column',
      severity: 'medium',
      title: 'Tray efficiency concerns',
      plantMetadata: 'CDU-03 · Column · Performance',
      updatedTimeAgo: 'Updated 5 days ago',
      status: 'resolved',
      statusLabel: 'Resolved',
      assignee: { initial: 'S', name: 'Sanjay', color: 'blue' },
    },
    {
      id: 'inv-007',
      code: '#INV-2024-007',
      tag: 'E-301',
      equipmentType: 'exchanger',
      severity: 'low',
      title: 'High pressure drop in Reboiler',
      plantMetadata: 'VDU-01 · Heat Exchanger · Delta P',
      updatedTimeAgo: 'Updated 6 days ago',
      status: 'resolved',
      statusLabel: 'Resolved',
      assignee: { initial: 'N', name: 'Narendar', color: 'blue' },
    },
  ],

  selectedInvestigation: {
    id: 'inv-001',
    code: '#INV-2024-001',
    tag: 'P-204',
    severity: 'high',
    title: 'High vibration in Crude Feed Pump',
    subtitle: 'CDU-03 · P-204 · Crude Feed Pump',
    status: 'open',
    statusLabel: 'Open',
    activeTab: 'overview',
    summary:
      'P-204 (Crude Feed Pump) is showing higher than normal vibration levels over the past week. The issue may be related to misalignment, bearing wear, or cavitation. Further analysis of vibration trends, operating conditions and maintenance history is required.',
    metadata: {
      equipmentTag: 'P-204',
      equipmentName: 'Crude Feed Pump',
      unitCode: 'CDU-03',
      unitName: 'Crude Distillation Unit',
      service: 'Crude Feed',
      status: 'Open',
      statusSubtext: 'Created',
      createdDate: '12 Jun 2024',
      createdTimeAgo: '2 hours ago',
      leadEngineer: 'Narendar',
      leadEngineerInitial: 'N',
    },
    keyMetrics: {
      name: 'Vibration (RMS)',
      value: '2.1 mm/s',
      unit: 'mm/s',
      normalRange: '0.5 - 1.2 mm/s',
      currentValue: '2.1 mm/s',
      threshold: '1.5 mm/s',
      trend: 'Increasing',
      trendDirection: 'increasing',
      chartData: [0.7, 0.9, 0.8, 1.1, 1.0, 1.4, 1.6, 1.5, 1.9, 2.1],
    },
    evidenceList: [
      {
        id: 'ev-1',
        name: 'P-204_Vibration_Trend.pdf',
        description: 'Vibration data',
        fileType: 'pdf',
      },
      {
        id: 'ev-2',
        name: 'P-204_Inspection_Report.pdf',
        description: 'Inspection report',
        fileType: 'pdf',
      },
      {
        id: 'ev-3',
        name: 'P-204_Maintenance_History.xlsx',
        description: 'Maintenance history',
        fileType: 'xlsx',
      },
      {
        id: 'ev-4',
        name: 'P-204_Picture_01.jpg',
        description: 'Equipment photo',
        fileType: 'jpg',
      },
    ],
    context: {
      plant: 'MRPL Refinery',
      unit: 'CDU-03',
      equipment: 'P-204',
      investigationId: '#INV-2024-001',
    },
  },

  suggestedActions: [
    {
      id: 'act-vib',
      text: 'Analyze vibration trend →',
      promptQuery: 'Analyze vibration trend for P-204 Crude Feed Pump',
    },
    {
      id: 'act-causes',
      text: 'Possible root causes →',
      promptQuery: 'Identify possible root causes for high vibration in P-204',
    },
    {
      id: 'act-maint',
      text: 'Check maintenance history →',
      promptQuery: 'Review maintenance history and past work orders for P-204',
    },
    {
      id: 'act-compare',
      text: 'Compare with similar equipment →',
      promptQuery: 'Compare P-204 performance with other crude feed pumps in CDU',
    },
  ],
}

export const DEFAULT_ANALYSIS_DETAIL_DATA: InvestigationAnalysisDetailData = {
  code: 'INV-2024-001',
  title: 'High vibration in Crude Feed Pump',
  tag: 'P-204',
  unit: 'CDU-03',
  service: 'Crude Feed',
  equipmentName: 'Crude Feed Pump',
  equipmentType: 'Centrifugal Pump',
  manufacturer: 'KSB',
  model: 'ETN 150-400',
  equipmentStatus: 'In Service',
  createdDate: 'Created 12 Jan 2024',
  updatedTimeAgo: 'Updated 2 hours ago',
  severity: 'high',
  status: 'open',
  statusLabel: 'Open',

  currentStage: 'investigate',
  stages: [
    { step: 1, key: 'investigate', label: 'Investigate', status: 'active' },
    { step: 2, key: 'analyze', label: 'Analyze', status: 'upcoming' },
    { step: 3, key: 'recommend', label: 'Recommend', status: 'upcoming' },
    { step: 4, key: 'report', label: 'Report', status: 'upcoming' },
  ],

  activeWorkspaceTab: 'analysis',
  activeAgentPreset: 'Standard',

  userRequest: {
    sender: 'You',
    timeAgo: '2 hours ago',
    text: 'Analyze the vibration data of P-204 and find possible root causes. Consider recent maintenance history and compare with similar pumps.',
  },

  aiResponse: {
    sender: 'Hyperion',
    timeAgo: '2 hours ago',
    statusText: 'Analysis complete',
    text: 'I have analyzed the vibration data for P-204 (Crude Feed Pump) and identified key patterns, potential root causes, and recommendations based on equipment history and similar pumps in the CDU unit.',
    activeSubTab: 'findings',
    keyFindings: [
      'Overall vibration (RMS) has increased from 1.1 mm/s to 2.1 mm/s over the past 7 days.',
      'Highest vibration observed in radial direction (H) at 2.3 mm/s.',
      'Frequency spectrum shows dominant peak at 1x running speed (48.5 Hz) and secondary peak at 2x.',
      'Recent maintenance (04 Jan 2024) included bearing lubrication, but no alignment check was performed.',
      'Similar pumps (P-101 A/B) operate at ~0.8–1.2 mm/s under normal conditions.',
    ],
    vibrationTrend: {
      timeRange: '7D',
      defaultTooltipIndex: 20, // 16 Jan 2024, 10:00
      points: [
        { dateLabel: '06 Jan', fullDate: '06 Jan 2024', h: 1.15, v: 0.95, a: 0.72 },
        { dateLabel: '', fullDate: '06 Jan 2024, 12:00', h: 1.25, v: 1.02, a: 0.75 },
        { dateLabel: '', fullDate: '07 Jan 2024, 00:00', h: 1.18, v: 0.98, a: 0.74 },
        { dateLabel: '', fullDate: '07 Jan 2024, 12:00', h: 1.30, v: 1.05, a: 0.78 },
        { dateLabel: '08 Jan', fullDate: '08 Jan 2024', h: 1.22, v: 1.00, a: 0.76 },
        { dateLabel: '', fullDate: '08 Jan 2024, 12:00', h: 1.35, v: 1.08, a: 0.80 },
        { dateLabel: '', fullDate: '09 Jan 2024, 00:00', h: 1.28, v: 1.02, a: 0.78 },
        { dateLabel: '', fullDate: '09 Jan 2024, 12:00', h: 1.42, v: 1.12, a: 0.82 },
        { dateLabel: '10 Jan', fullDate: '10 Jan 2024', h: 1.32, v: 1.06, a: 0.79 },
        { dateLabel: '', fullDate: '10 Jan 2024, 12:00', h: 1.48, v: 1.15, a: 0.84 },
        { dateLabel: '', fullDate: '11 Jan 2024, 00:00', h: 1.38, v: 1.08, a: 0.81 },
        { dateLabel: '', fullDate: '11 Jan 2024, 12:00', h: 1.58, v: 1.22, a: 0.86 },
        { dateLabel: '12 Jan', fullDate: '12 Jan 2024', h: 1.48, v: 1.16, a: 0.84 },
        { dateLabel: '', fullDate: '12 Jan 2024, 12:00', h: 1.68, v: 1.28, a: 0.89 },
        { dateLabel: '', fullDate: '13 Jan 2024, 00:00', h: 1.55, v: 1.20, a: 0.85 },
        { dateLabel: '', fullDate: '13 Jan 2024, 12:00', h: 1.82, v: 1.38, a: 0.92 },
        { dateLabel: '14 Jan', fullDate: '14 Jan 2024', h: 1.68, v: 1.30, a: 0.88 },
        { dateLabel: '', fullDate: '14 Jan 2024, 12:00', h: 1.95, v: 1.45, a: 0.96 },
        { dateLabel: '', fullDate: '15 Jan 2024, 00:00', h: 1.80, v: 1.36, a: 0.92 },
        { dateLabel: '', fullDate: '15 Jan 2024, 12:00', h: 2.12, v: 1.58, a: 1.02 },
        { dateLabel: '16 Jan', fullDate: '16 Jan 2024, 10:00', h: 2.30, v: 1.70, a: 1.10 },
        { dateLabel: '', fullDate: '16 Jan 2024, 18:00', h: 2.22, v: 1.64, a: 1.08 },
        { dateLabel: '', fullDate: '17 Jan 2024, 06:00', h: 2.15, v: 1.60, a: 1.05 },
        { dateLabel: '', fullDate: '17 Jan 2024, 18:00', h: 2.38, v: 1.72, a: 1.12 },
        { dateLabel: '18 Jan', fullDate: '18 Jan 2024', h: 2.32, v: 1.68, a: 1.09 },
      ],
    },
  },

  relatedDocuments: [
    {
      id: 'doc-1',
      name: 'P-204_Vibration_Trend.pdf',
      description: 'Vibration data · 16 Jan 2024',
      fileType: 'pdf',
    },
    {
      id: 'doc-2',
      name: 'P-204_Maintenance_History.pdf',
      description: 'Maintenance record · 04 Jan 2024',
      fileType: 'pdf',
    },
    {
      id: 'doc-3',
      name: 'P-204_Inspection_Report.pdf',
      description: 'Inspection report · 12 Dec 2023',
      fileType: 'pdf',
    },
    {
      id: 'doc-4',
      name: 'P-204_Datasheet.pdf',
      description: 'Equipment datasheet',
      fileType: 'pdf',
    },
    {
      id: 'doc-5',
      name: 'CDU-03_P&ID-001.pdf',
      description: 'P&ID drawing · Rev. 2',
      fileType: 'pdf',
    },
    {
      id: 'doc-6',
      name: 'Pump_Alignment_Guide.pdf',
      description: 'Maintenance procedure',
      fileType: 'pdf',
    },
  ],
  totalDocumentsCount: 6,

  similarEquipment: [
    {
      id: 'sim-1',
      tag: 'P-101 A',
      name: 'Crude Feed Pump',
      unit: 'CDU-03',
      metric: '0.9 mm/s',
      status: 'Normal',
      sparkline: [0.82, 0.88, 0.85, 0.9, 0.88],
    },
    {
      id: 'sim-2',
      tag: 'P-101 B',
      name: 'Crude Feed Pump',
      unit: 'CDU-03',
      metric: '1.0 mm/s',
      status: 'Normal',
      sparkline: [0.95, 0.98, 1.02, 0.99, 1.0],
    },
    {
      id: 'sim-3',
      tag: 'P-203',
      name: 'Crude Feed Pump',
      unit: 'CDU-03',
      metric: '1.2 mm/s',
      status: 'Normal',
      sparkline: [1.1, 1.14, 1.18, 1.16, 1.2],
    },
  ],
}
