import type {
  PIDEquipment,
  PIDLine,
  PIDDocument,
  PIDAreaNode,
} from './types'

export const initialEquipments: PIDEquipment[] = [
  {
    id: 'P-101AB',
    tag: 'P-101 A/B',
    name: 'Crude Feed Pump',
    type: 'Centrifugal Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description:
      'Main crude feed pump used to charge crude oil to the preheat train. Two units (A/B) with one in service and one standby.',
    specs: {
      Capacity: '450 m³/h',
      Head: '120 m',
      Power: '250 kW',
      RPM: '2950 RPM',
      Fluid: 'Desalted Crude',
      Temperature: '85 °C',
    },
    connectedLines: ['10"-CR-101', '10"-CR-102'],
    documents: ['CDU-03-001.pdf', 'P-101 Datasheet.pdf', 'P-101 Maintenance.pdf', 'Crude Pump Procedure.pdf', 'Vibration Report.pdf'],
  },
  {
    id: 'P-101A',
    tag: 'P-101 A',
    name: 'Crude Feed Pump A',
    type: 'Centrifugal Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Duty pump for primary crude oil transfer to preheat exchanger train E-101.',
    specs: { Flow: '450 m³/h', Motor: '250 kW Elec' },
  },
  {
    id: 'P-101B',
    tag: 'P-101 B',
    name: 'Crude Feed Pump B',
    type: 'Centrifugal Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'Standby',
    description: 'Auto-kickin standby pump for crude feed service.',
    specs: { Flow: '450 m³/h', Motor: '250 kW Elec' },
  },
  {
    id: 'E-101',
    tag: 'E-101',
    name: 'Crude Preheater 1',
    type: 'Heat Exchanger',
    service: 'Crude Preheat',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'First-stage shell and tube heat exchanger preheating crude using residue heat stream.',
    specs: { Duty: '14.5 MW', Area: '620 m²', ShellP: '18 bar' },
  },
  {
    id: 'E-102',
    tag: 'E-102',
    name: 'Crude Preheater 2',
    type: 'Heat Exchanger',
    service: 'Crude Preheat',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Second-stage heat exchanger prior to desalter feed stage.',
    specs: { Duty: '12.8 MW', Area: '580 m²' },
  },
  {
    id: 'E-103',
    tag: 'E-103',
    name: 'Crude Preheater 3',
    type: 'Heat Exchanger',
    service: 'Crude Preheat',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'High-temperature preheat exchangers before fired heater inlet.',
    specs: { Duty: '16.2 MW', Area: '710 m²' },
  },
  {
    id: 'T-101',
    tag: 'T-101',
    name: 'Crude Distillation Column',
    type: 'Distillation Column',
    service: 'Main Fractionation',
    unit: 'CDU-03',
    area: '200 - Crude Column',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Atmospheric crude distillation column separating crude oil into LPG, naphtha, kerosene, diesel, and atmospheric residue.',
    specs: { Height: '48 m', Diameter: '4.2 m', Trays: '42 Valve Trays' },
  },
  {
    id: 'E-201',
    tag: 'E-201',
    name: 'Reboiler Exchanger',
    type: 'Heat Exchanger',
    service: 'Column Reboil',
    unit: 'CDU-03',
    area: '200 - Crude Column',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Thermosiphon reboiler supplying heat duty to column bottom section.',
  },
  {
    id: 'V-201',
    tag: 'V-201',
    name: 'Reflux Drum',
    type: 'Pressure Vessel',
    service: 'Overhead Separator',
    unit: 'CDU-03',
    area: '300 - Overhead',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Overhead condensed vapor separator collecting light naphtha condensate and sour water.',
  },
  {
    id: 'E-301',
    tag: 'E-301',
    name: 'Overhead Condenser',
    type: 'Heat Exchanger',
    service: 'Vapor Condensing',
    unit: 'CDU-03',
    area: '300 - Overhead',
    pid: 'CDU-03-001',
    status: 'In Service',
    description: 'Fin-fan air cooler condensing column overhead vapors before reflux drum.',
  },
]

export const initialLines: PIDLine[] = [
  {
    id: 'L-101',
    lineNo: '10"-CR-101',
    service: 'Crude Feed',
    from: 'Tank-01',
    to: 'P-101 A/B',
    size: '10 Inch',
    spec: 'A1A-CS',
  },
  {
    id: 'L-102',
    lineNo: '10"-CR-102',
    service: 'Crude Feed',
    from: 'P-101 A/B',
    to: 'E-101',
    size: '10 Inch',
    spec: 'A1A-CS',
  },
  {
    id: 'L-103',
    lineNo: '8"-CR-103',
    service: 'Crude Feed',
    from: 'E-101',
    to: 'E-102',
    size: '8 Inch',
    spec: 'A1A-CS',
  },
  {
    id: 'L-104',
    lineNo: '8"-CR-104',
    service: 'Crude Feed',
    from: 'E-102',
    to: 'T-101',
    size: '8 Inch',
    spec: 'A1A-CS',
  },
]

export const initialDocuments: PIDDocument[] = [
  {
    id: 'D-001',
    fileName: 'CDU-03-001.pdf',
    title: 'P&ID Diagram - Crude Preheat & Charge',
    type: 'P&ID',
    date: '12 Jan 2024',
    fileSize: '4.2 MB',
    tagRef: 'CDU-03',
  },
  {
    id: 'D-002',
    fileName: 'P-101 Datasheet.pdf',
    title: 'Crude Feed Pump Mechanical Datasheet',
    type: 'Datasheet',
    date: '08 Feb 2024',
    fileSize: '1.8 MB',
    tagRef: 'P-101 A/B',
  },
  {
    id: 'D-003',
    fileName: 'P-101 Maintenance.pdf',
    title: 'P-101 A/B Bearing & Seal Maintenance Log',
    type: 'Maintenance',
    date: '15 Mar 2024',
    fileSize: '2.5 MB',
    tagRef: 'P-101 A/B',
  },
  {
    id: 'D-004',
    fileName: 'Crude Pump Procedure.pdf',
    title: 'Standard Operating Procedure - Pump Switching',
    type: 'Procedure',
    date: '21 Mar 2024',
    fileSize: '1.1 MB',
    tagRef: 'P-101 A/B',
  },
  {
    id: 'D-005',
    fileName: 'Vibration Report.pdf',
    title: 'Quarterly Vibration & Thermography Inspection',
    type: 'Inspection',
    date: '04 Apr 2024',
    fileSize: '3.4 MB',
    tagRef: 'P-101 A/B',
  },
  {
    id: 'D-006',
    fileName: 'E-101 Thermal Specs.pdf',
    title: 'E-101 Thermal & Hydraulic Design Calculation',
    type: 'Design Spec',
    date: '10 Jan 2024',
    fileSize: '2.2 MB',
    tagRef: 'E-101',
  },
  {
    id: 'D-007',
    fileName: 'T-101 Tray Design.pdf',
    title: 'T-101 Column Internal Tray Specification',
    type: 'Design Spec',
    date: '14 Jan 2024',
    fileSize: '5.1 MB',
    tagRef: 'T-101',
  },
  {
    id: 'D-008',
    fileName: 'Reflux Control Philosophy.pdf',
    title: 'Reflux Drum V-201 Level & Pressure Control',
    type: 'Control Philosophy',
    date: '18 Feb 2024',
    fileSize: '1.4 MB',
    tagRef: 'V-201',
  },
  {
    id: 'D-009',
    fileName: 'CDU-03 HAZOP Study.pdf',
    title: 'Crude Distillation Unit Risk & Safety Study',
    type: 'Procedure',
    date: '05 Jan 2024',
    fileSize: '8.7 MB',
  },
  {
    id: 'D-010',
    fileName: 'P-101 Seal Inspection.pdf',
    title: 'Mechanical Seal Flush Plan Inspection',
    type: 'Inspection',
    date: '28 Feb 2024',
    fileSize: '1.6 MB',
    tagRef: 'P-101 A/B',
  },
  {
    id: 'D-011',
    fileName: 'CDU-03 Operating Manual.pdf',
    title: 'CDU-03 Complete Unit Operations Manual',
    type: 'Procedure',
    date: '01 Feb 2024',
    fileSize: '12.4 MB',
  },
  {
    id: 'D-012',
    fileName: 'P-101 Motor Spec.pdf',
    title: '250kW Electric Motor Electrical Datasheet',
    type: 'Datasheet',
    date: '19 Feb 2024',
    fileSize: '0.9 MB',
    tagRef: 'P-101 A/B',
  },
]

export const areaNodes: PIDAreaNode[] = [
  {
    id: 'area-100',
    name: 'Area 100 - Crude Preheat',
    code: '100',
    categories: [
      { id: 'cat-exchangers-100', name: 'Heat Exchangers', items: ['E-101', 'E-102', 'E-103'] },
      { id: 'cat-pumps-100', name: 'Pumps', items: ['P-101AB', 'P-101A', 'P-101B'] },
      { id: 'cat-valves-100', name: 'Valves', items: ['VLV-101', 'VLV-102'] },
      { id: 'cat-inst-100', name: 'Instruments', items: ['FIT-101', 'PIT-101'] },
    ],
  },
  {
    id: 'area-200',
    name: 'Area 200 - Crude Column',
    code: '200',
    categories: [
      { id: 'cat-columns-200', name: 'Columns', items: ['T-101'] },
      { id: 'cat-exchangers-200', name: 'Heat Exchangers', items: ['E-201'] },
      { id: 'cat-valves-200', name: 'Valves', items: ['VLV-201'] },
      { id: 'cat-inst-200', name: 'Instruments', items: ['TIT-201', 'LIC-201'] },
    ],
  },
  {
    id: 'area-300',
    name: 'Area 300 - Overhead',
    code: '300',
    categories: [
      { id: 'cat-exchangers-300', name: 'Condenser', items: ['E-301'] },
      { id: 'cat-vessels-300', name: 'Reflux Drum', items: ['V-201'] },
      { id: 'cat-inst-300', name: 'Instruments', items: ['PIC-301', 'FI-301'] },
    ],
  },
]
