// Faithful static-site port of Originkit Hex Comb's shader geometry and interaction.
// Source inspected at originkit.dev/components/hex-comb; only color uniforms are rethemed.
const VERTEX=`attribute vec2 aPos;void main(){gl_Position=vec4(aPos,0.,1.);}`;
const FRAGMENT=`
precision highp float;
uniform vec2 uRes;uniform float uTime,uDpr,uScale,uApothem,uPerp,uLift,uSwell,uReach,uPointerAmt,uGrain,uVignette;uniform vec2 uPointer;uniform vec3 uBg,uBase,uAccent;
const vec2 E=vec2(.4200,.9075),PP=vec2(-.9075,.4200),L=vec2(-.5548,.8320),N0=vec2(1.,0.),N1=vec2(.5,.8660254),N2=vec2(-.5,.8660254);const float ROW=1.7320508,CIRC=1.1547005;
float h21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float grain(vec2 p,float t){vec2 c=floor(p/max(uDpr,1.));return h21(c+floor(t*24.)*13.7)-.5;}float hexD(vec2 q,float a){return max(max(abs(dot(q,N0)),abs(dot(q,N1))),abs(dot(q,N2)))-a;}float hullD(vec2 q,float a,float h){vec3 d=vec3(dot(N0,E),dot(N1,E),dot(N2,E))*h;vec3 s=vec3(dot(q,N0),dot(q,N1),dot(q,N2));float m=abs(dot(q,PP))-uPerp*a;m=max(m,max(s.x-a-max(0.,d.x),-s.x-a-max(0.,-d.x)));m=max(m,max(s.y-a-max(0.,d.y),-s.y-a-max(0.,-d.y)));m=max(m,max(s.z-a-max(0.,d.z),-s.z-a-max(0.,-d.z)));return m;}float cellHeight(vec2 c){float d=length(c-uPointer)/max(uReach,.001);float bump=exp(-d*d*2.2);float w=.5+.5*sin(dot(c,vec2(.21,.13))+h21(c*.37)*6.283-uTime*.8);return uLift*uPointerAmt*bump+uSwell*w;}
void main(){vec2 uv=gl_FragCoord.xy/uRes;float aspect=uRes.x/uRes.y;vec2 p=vec2(uv.x*aspect,uv.y)*uScale;float unitPx=uRes.y/uScale,aa=1.4/unitPx,a=uApothem,ceiling=max(uLift+uSwell,.001);vec3 col=uBg;float j0=floor(p.y/ROW+.5);for(int dj=1;dj>=-3;dj--){float fj=j0+float(dj),par=mod(fj,2.),cy=fj*ROW,i0=floor((p.x-par)*.5+.5);for(int di=-1;di<=1;di++){vec2 c=vec2((i0+float(di))*2.+par,cy),q=p-c;float h=cellHeight(c),bound=CIRC+h+.42;if(dot(q,q)>bound*bound)continue;if(h>.02){float ds=hullD(q+vec2(.11,.17),a,h),sh=1.-smoothstep(-.02,.36,ds);col*=1.-.55*sh*clamp(h*1.7,0.,1.);}float dh=hullD(q,a,h),cov=1.-smoothstep(-aa,aa,dh);if(cov<=0.)continue;float dt=hexD(q-h*E,a),top=1.-smoothstep(-aa,aa,dt),wall=clamp(cov-top,0.,1.),hn=clamp(h/ceiling,0.,1.);if(wall>0.){vec3 s=vec3(dot(q,N0),dot(q,N1),dot(q,N2));vec2 wn=N0*sign(s.x);float best=abs(s.x);if(abs(s.y)>best){best=abs(s.y);wn=N1*sign(s.y);}if(abs(s.z)>best){wn=N2*sign(s.z);}float lam=clamp(dot(wn,L)*.5+.5,0.,1.),depth=clamp(dot(q-h*E,-E)/max(h,.001),0.,1.);vec3 wc=mix(uBg,uBase,.12+.74*lam)*(1.-.62*depth);col=mix(col,wc,wall);}if(top>0.){vec2 qt=(q-h*E)/max(a,.001);vec3 rest=mix(uBg,uBase,.20),risen=mix(uBase*1.25,uAccent,smoothstep(.58,1.,hn)),tc=mix(rest,risen,smoothstep(0.,.45,hn));tc*=.86+.16*dot(qt,L);float rim=smoothstep(-aa*3.5,-aa,dt)*(1.-smoothstep(-aa,aa,dt));tc+=rim*mix(uBase,uAccent,hn)*(.30+.75*hn);col=mix(col,tc,top);}}}vec2 v=uv-.5;v.x*=aspect;col*=1.-uVignette*smoothstep(.34,1.,length(v));col+=(h21(gl_FragCoord.xy)-.5)*(1.5/255.);col+=grain(gl_FragCoord.xy,uTime)*uGrain;gl_FragColor=vec4(clamp(col,0.,1.),1.);}`;
function rgb(hex){const n=parseInt(hex.slice(1),16);return [(n>>16&255)/255,(n>>8&255)/255,(n&255)/255]}
export function mountHexComb(canvas){
 const gl=canvas.getContext('webgl',{antialias:false,alpha:false,depth:false});if(!gl)return;
 const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,VERTEX));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,FRAGMENT));gl.linkProgram(program);gl.useProgram(program);
 const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'aPos');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);
 const u=n=>gl.getUniformLocation(program,n);const U=['uRes','uTime','uDpr','uBg','uBase','uAccent','uScale','uApothem','uPerp','uLift','uSwell','uReach','uPointer','uPointerAmt','uGrain','uVignette'].reduce((o,n)=>(o[n]=u(n),o),{});
 let w=1,h=1,raf,visible=true,t0=performance.now(),pointer={x:.5,y:.5,target:0,amount:0};const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);w=Math.max(1,Math.floor(r.width*dpr));h=Math.max(1,Math.floor(r.height*dpr));canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}new ResizeObserver(resize).observe(canvas);resize();
 canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width;pointer.y=1-(e.clientY-r.top)/r.height;pointer.target=1});canvas.addEventListener('pointerleave',()=>pointer.target=0);
 const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible&&!raf)render()},{threshold:.02});observer.observe(canvas);document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible&&!raf)render()});
 function render(now=performance.now()){if(!visible){raf=0;return}pointer.amount+=(pointer.target-pointer.amount)*.09;const time=reduce?0:(now-t0)/1000;gl.uniform2f(U.uRes,w,h);gl.uniform1f(U.uTime,time);gl.uniform1f(U.uDpr,Math.min(devicePixelRatio||1,1.5));gl.uniform3fv(U.uBg,rgb('#070C16'));gl.uniform3fv(U.uBase,rgb('#263247'));gl.uniform3fv(U.uAccent,rgb('#FDDA98'));gl.uniform1f(U.uScale,9);gl.uniform1f(U.uApothem,.88);gl.uniform1f(U.uPerp,1.15001227);gl.uniform1f(U.uLift,.85);gl.uniform1f(U.uSwell,reduce?0:.18);gl.uniform1f(U.uReach,3.2);gl.uniform2f(U.uPointer,pointer.x*(w/h)*9,pointer.y*9);gl.uniform1f(U.uPointerAmt,pointer.amount);gl.uniform1f(U.uGrain,.008);gl.uniform1f(U.uVignette,.38);gl.drawArrays(gl.TRIANGLES,0,3);raf=requestAnimationFrame(render)}render();
}