/**
 * Mock data for the HYPERION Documents workbench matching images/Documents.jpeg.
 * @module @deepseek-ai/dsh-client-ui-conversation/client/documents/mockData
 */

import type { DocumentCategory, DocumentItem } from './types.ts'

export const DOCUMENT_CATEGORIES: readonly DocumentCategory[] = [
  {
    id: 'pid',
    title: 'P&ID Drawings',
    count: 428,
    color: '#8b5cf6',
    iconType: 'drawing',
  },
  {
    id: 'equipment',
    title: 'Equipment Docs',
    count: 1264,
    color: '#3b82f6',
    iconType: 'document',
  },
  {
    id: 'procedures',
    title: 'Procedures',
    count: 312,
    color: '#10b981',
    iconType: 'procedure',
  },
  {
    id: 'maintenance',
    title: 'Maintenance',
    count: 186,
    color: '#f59e0b',
    iconType: 'maintenance',
  },
  {
    id: 'reports',
    title: 'Reports',
    count: 98,
    color: '#a855f7',
    iconType: 'report',
  },
  {
    id: 'standards',
    title: 'Standards',
    count: 74,
    color: '#f43f5e',
    iconType: 'standard',
  },
]

export const MOCK_DOCUMENTS: readonly DocumentItem[] = [
  {
    id: 'CDU-03-001',
    name: 'CDU-03-001.pdf',
    subtitle: 'Crude Distillation Unit - P&ID',
    type: 'P&ID',
    typeColor: 'purple',
    iconColor: 'red',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    equipment: 'T-101 / P-101 A/B',
    date: '12 Jan 2024',
    size: '4.8 MB',
    revision: 'Rev. 2',
    uploadedBy: 'Narendar',
    tags: ['P&ID', 'CDU', 'Crude Feed', 'Rev.2'],
    pageCount: 12,
  },
  {
    id: 'P-101_Datasheet',
    name: 'P-101_Datasheet.pdf',
    subtitle: 'Crude Feed Pump',
    type: 'Datasheet',
    typeColor: 'blue',
    iconColor: 'purple',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    equipment: 'P-101 A/B',
    date: '08 Feb 2024',
    size: '2.1 MB',
    revision: 'Rev. 1',
    uploadedBy: 'Narendar',
    tags: ['Datasheet', 'Pump', 'CDU'],
    pageCount: 6,
  },
  {
    id: 'P-101_Maintenance_Manual',
    name: 'P-101_Maintenance_Manual.pdf',
    subtitle: 'Crude Feed Pump',
    type: 'Manual',
    typeColor: 'green',
    iconColor: 'blue',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    equipment: 'P-101 A/B',
    date: '15 Mar 2024',
    size: '12.4 MB',
    revision: 'Rev. 3',
    uploadedBy: 'Narendar',
    tags: ['Manual', 'Pump', 'Maintenance'],
    pageCount: 48,
  },
  {
    id: 'Operating_Procedure_CDU',
    name: 'Operating_Procedure_CDU.pdf',
    subtitle: 'CDU - Start up Procedure',
    type: 'Procedure',
    typeColor: 'orange',
    iconColor: 'orange',
    unit: 'CDU',
    area: 'CDU Area',
    equipment: 'CDU Units',
    date: '21 Mar 2024',
    size: '3.5 MB',
    revision: 'Rev. 4',
    uploadedBy: 'Narendar',
    tags: ['Procedure', 'Operating', 'CDU'],
    pageCount: 22,
  },
  {
    id: 'Inspection_Report_P-204',
    name: 'Inspection_Report_P-204.pdf',
    subtitle: 'Vibration Inspection Report',
    type: 'Inspection',
    typeColor: 'rose',
    iconColor: 'red',
    unit: 'P-204',
    area: 'Utilities',
    equipment: 'P-204',
    date: '04 Apr 2024',
    size: '1.8 MB',
    revision: 'Rev. 1',
    uploadedBy: 'Narendar',
    tags: ['Inspection', 'Vibration', 'Report'],
    pageCount: 14,
  },
  {
    id: 'Pump_Alignment_Guide',
    name: 'Pump_Alignment_Guide.pdf',
    subtitle: 'Maintenance Procedure',
    type: 'Guide',
    typeColor: 'cyan',
    iconColor: 'blue',
    unit: 'P-101 A/B',
    area: 'Maintenance',
    equipment: 'P-101 A/B',
    date: '18 May 2024',
    size: '5.2 MB',
    revision: 'Rev. 2',
    uploadedBy: 'Narendar',
    tags: ['Guide', 'Alignment', 'Pump'],
    pageCount: 16,
  },
  {
    id: 'HCU-01_P&ID-002',
    name: 'HCU-01_P&ID-002.pdf',
    subtitle: 'Hydrocracking Unit - P&ID',
    type: 'P&ID',
    typeColor: 'purple',
    iconColor: 'purple',
    unit: 'HCU-01',
    area: 'Hydrocracker',
    equipment: 'HCU-01',
    date: '02 Jun 2024',
    size: '6.1 MB',
    revision: 'Rev. 1',
    uploadedBy: 'Narendar',
    tags: ['P&ID', 'HCU', 'Drawing'],
    pageCount: 18,
  },
  {
    id: 'Safety_Permit_Procedure',
    name: 'Safety_Permit_Procedure.pdf',
    subtitle: 'Hot Work Permit',
    type: 'Safety',
    typeColor: 'orange',
    iconColor: 'orange',
    unit: 'All Units',
    area: 'HSE',
    equipment: 'Plant-wide',
    date: '12 Jun 2024',
    size: '850 KB',
    revision: 'Rev. 5',
    uploadedBy: 'Narendar',
    tags: ['Safety', 'Permit', 'Procedure'],
    pageCount: 8,
  },
  {
    id: 'Vendor_Catalog_Pumps',
    name: 'Vendor_Catalog_Pumps.pdf',
    subtitle: 'Centrifugal Pump Catalog',
    type: 'Catalog',
    typeColor: 'blue',
    iconColor: 'blue',
    unit: 'Pumps',
    area: 'Vendor',
    equipment: 'Centrifugal Pumps',
    date: '25 Jun 2024',
    size: '18.3 MB',
    revision: 'Rev. 1',
    uploadedBy: 'Narendar',
    tags: ['Catalog', 'Vendor', 'Pumps'],
    pageCount: 120,
  },
  {
    id: 'AsBuilt_CDU-03',
    name: 'AsBuilt_CDU-03.pdf',
    subtitle: 'As Built Drawing',
    type: 'Drawing',
    typeColor: 'gray',
    iconColor: 'teal',
    unit: 'CDU-03',
    area: 'CDU-03',
    equipment: 'CDU-03 Full',
    date: '10 Jul 2024',
    size: '9.4 MB',
    revision: 'Rev. 0',
    uploadedBy: 'Narendar',
    tags: ['Drawing', 'AsBuilt', 'CDU'],
    pageCount: 34,
  },
]
