/**
 * Document catalog for the HYPERION Documents workbench.
 * Entries are REAL refinery-corpus records (refinery-corpus/manifest/documents.json):
 * titles, organizations, dates, page counts, sizes and source URLs are transcribed
 * from the manifest — nothing here is invented. Viewer text for small documents
 * comes from refinery-corpus/corpus/processed/*.json via ./corpusText.ts.
 * DOC-012 is TRAINING material (OER symbols reference), explicitly labeled — it is
 * not an MRPL as-built drawing.
 * @module @deepseek-ai/dsh-client-ui-conversation/client/documents/mockData
 */

import type { DocumentCategory, DocumentItem } from './types.ts'

export const DOCUMENT_CATEGORIES: readonly DocumentCategory[] = [
  {
    id: 'pid',
    title: 'P&ID Reference',
    count: 1,
    color: '#8b5cf6',
    iconType: 'drawing',
  },
  {
    id: 'equipment',
    title: 'Incident Case Studies',
    count: 4,
    color: '#3b82f6',
    iconType: 'document',
  },
  {
    id: 'procedures',
    title: 'Alerts & Permits',
    count: 3,
    color: '#10b981',
    iconType: 'procedure',
  },
  {
    id: 'maintenance',
    title: 'CSB Investigations',
    count: 2,
    color: '#f59e0b',
    iconType: 'maintenance',
  },
  {
    id: 'reports',
    title: 'Process & Energy',
    count: 1,
    color: '#a855f7',
    iconType: 'report',
  },
  {
    id: 'standards',
    title: 'Product Specs',
    count: 2,
    color: '#f43f5e',
    iconType: 'standard',
  },
]

export const MOCK_DOCUMENTS: readonly DocumentItem[] = [
  {
    id: 'DOC-001',
    corpusId: 'DOC-001',
    name: 'DOC-001.pdf',
    subtitle: 'Fire Incident in Crude and Vacuum Distillation Unit (CDU/VDU)',
    type: 'Case Study',
    typeColor: 'orange',
    iconColor: 'red',
    unit: 'CDU/VDU',
    area: 'Preheat Exchangers',
    equipment: 'CRUDE/HVGO Exchanger',
    date: '2026-06-01',
    size: '1.2 MB',
    revision: '',
    uploadedBy: 'OISD (MoPNG, India)',
    tags: ['Case Study', 'CDU', 'Fire', 'OISD'],
    pageCount: 8,
    sourceOrg: 'Oil Industry Safety Directorate (MoPNG, India)',
    sourceUrl: 'https://oisd.gov.in/Image/GetCaseStudyAttachment?caseStudyID=83',
    authenticity: 'government',
  },
  {
    id: 'DOC-002',
    corpusId: 'DOC-002',
    name: 'DOC-002.pdf',
    subtitle: 'Fire in 2-inch hydrocarbon drain line',
    type: 'Case Study',
    typeColor: 'orange',
    iconColor: 'red',
    unit: 'Refinery-wide',
    area: 'Drain Systems',
    equipment: '2-in. Hydrocarbon Drain',
    date: '2025-11-07',
    size: '404 KB',
    revision: '',
    uploadedBy: 'OISD (MoPNG, India)',
    tags: ['Case Study', 'Drain Line', 'Fire', 'OISD'],
    pageCount: 3,
    sourceOrg: 'Oil Industry Safety Directorate (MoPNG, India)',
    sourceUrl: 'https://oisd.gov.in/Image/GetCaseStudyAttachment?caseStudyID=84',
    authenticity: 'government',
  },
  {
    id: 'DOC-003',
    corpusId: 'DOC-003',
    name: 'DOC-003.pdf',
    subtitle: 'Hydrogen Sulfide exposure fatality on external floating roof tank deck',
    type: 'Case Study',
    typeColor: 'orange',
    iconColor: 'red',
    unit: 'Tank Farm',
    area: 'Floating Roof Tank',
    equipment: 'Storage Tank Deck',
    date: '2025-09-15',
    size: '391 KB',
    revision: '',
    uploadedBy: 'OISD (MoPNG, India)',
    tags: ['Case Study', 'H2S', 'Tank Farm', 'OISD'],
    pageCount: 3,
    sourceOrg: 'Oil Industry Safety Directorate (MoPNG, India)',
    sourceUrl: 'https://oisd.gov.in/Image/GetCaseStudyAttachment?caseStudyID=85',
    authenticity: 'government',
  },
  {
    id: 'DOC-004',
    corpusId: 'DOC-004',
    name: 'DOC-004.pdf',
    subtitle: 'Fire incident during maintenance activity',
    type: 'Case Study',
    typeColor: 'orange',
    iconColor: 'red',
    unit: 'Refinery-wide',
    area: 'Maintenance',
    equipment: 'Process Equipment',
    date: '2025-03-11',
    size: '705 KB',
    revision: '',
    uploadedBy: 'OISD (MoPNG, India)',
    tags: ['Case Study', 'Maintenance', 'Fire', 'OISD'],
    pageCount: 4,
    sourceOrg: 'Oil Industry Safety Directorate (MoPNG, India)',
    sourceUrl: 'https://oisd.gov.in/Image/GetCaseStudyAttachment?caseStudyID=66',
    authenticity: 'government',
  },
  {
    id: 'DOC-005',
    corpusId: 'DOC-005',
    name: 'DOC-005.pdf',
    subtitle: 'Fatal incident during painting of internal roof of storage tank',
    type: 'Safety Alert',
    typeColor: 'rose',
    iconColor: 'orange',
    unit: 'Tank Farm',
    area: 'Storage Tank',
    equipment: 'Tank Internal Roof',
    date: '2026-06-08',
    size: '261 KB',
    revision: '',
    uploadedBy: 'OISD (MoPNG, India)',
    tags: ['Safety Alert', 'Tank Farm', 'OISD'],
    pageCount: 2,
    sourceOrg: 'Oil Industry Safety Directorate (MoPNG, India)',
    sourceUrl: 'https://oisd.gov.in/Image/GetSafetyAlertAttachmentByID?safetyAlertID=66',
    authenticity: 'government',
  },
  {
    id: 'DOC-006',
    corpusId: 'DOC-006',
    name: 'DOC-006.pdf',
    subtitle: 'Incident during pit excavation work for pipeline inspection',
    type: 'Safety Alert',
    typeColor: 'rose',
    iconColor: 'orange',
    unit: 'Refinery-wide',
    area: 'Pipeline ROW',
    equipment: 'Pipeline',
    date: '2026-04-28',
    size: '425 KB',
    revision: '',
    uploadedBy: 'OISD (MoPNG, India)',
    tags: ['Safety Alert', 'Excavation', 'OISD'],
    pageCount: 3,
    sourceOrg: 'Oil Industry Safety Directorate (MoPNG, India)',
    sourceUrl: 'https://oisd.gov.in/Image/GetSafetyAlertAttachmentByID?safetyAlertID=56',
    authenticity: 'government',
  },
  {
    id: 'DOC-007',
    corpusId: 'DOC-007',
    name: 'DOC-007.pdf',
    subtitle: 'Chevron Richmond Refinery #4 Crude Unit pipe rupture and fire',
    type: 'Investigation',
    typeColor: 'rose',
    iconColor: 'red',
    unit: '#4 Crude Unit',
    area: 'Richmond Refinery (CSB)',
    equipment: 'Crude Unit Piping',
    date: '2015-01-28',
    size: '7.7 MB',
    revision: 'Final',
    uploadedBy: 'U.S. Chemical Safety Board',
    tags: ['Investigation', 'Crude Unit', 'CSB'],
    pageCount: 132,
    sourceOrg: 'U.S. Chemical Safety Board',
    sourceUrl: 'https://www.csb.gov/assets/1/17/chevron_final_investigation_report_2015-01-28.pdf',
    authenticity: 'government',
    viewerNote: 'Full text lives in the source corpus (132 pages); viewer shows the catalog record.',
  },
  {
    id: 'DOC-008',
    corpusId: 'DOC-008',
    name: 'DOC-008.pdf',
    subtitle: 'Tesoro Anacortes Refinery heat exchanger rupture',
    type: 'Investigation',
    typeColor: 'rose',
    iconColor: 'red',
    unit: 'Refinery',
    area: 'Anacortes (CSB)',
    equipment: 'Heat Exchanger',
    date: '2014-05-01',
    size: '6.3 MB',
    revision: 'Final',
    uploadedBy: 'U.S. Chemical Safety Board',
    tags: ['Investigation', 'Exchanger', 'CSB'],
    pageCount: 160,
    sourceOrg: 'U.S. Chemical Safety Board',
    sourceUrl: 'https://www.csb.gov/assets/1/7/tesoro_anacortes_2014-may-01.pdf',
    authenticity: 'government',
    viewerNote: 'Full text lives in the source corpus (160 pages); viewer shows the catalog record.',
  },
  {
    id: 'DOC-009',
    corpusId: 'DOC-009',
    name: 'DOC-009.html',
    subtitle: 'OSHA 29 CFR 1910.119 Process Safety Management (incl. Hot Work Permit)',
    type: 'Work Permit',
    typeColor: 'orange',
    iconColor: 'orange',
    unit: 'Refinery-wide',
    area: 'HSE Compliance',
    equipment: 'Hot Work Permits',
    date: '—',
    size: '186 KB',
    revision: '',
    uploadedBy: 'U.S. OSHA',
    tags: ['Work Permit', 'PSM', 'OSHA'],
    pageCount: 0,
    sourceOrg: 'U.S. Occupational Safety and Health Administration',
    sourceUrl: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.119',
    authenticity: 'government',
    viewerNote: 'HTML capture; extracted text is not embedded in the viewer.',
  },
  {
    id: 'DOC-010',
    corpusId: 'DOC-010',
    name: 'DOC-010.pdf',
    subtitle: 'MRPL Specification for Motor Gasoline BS-IV (IS 2796:2008 Amd.1, MG 91)',
    type: 'Spec Sheet',
    typeColor: 'blue',
    iconColor: 'blue',
    unit: 'Fuels Blending',
    area: 'MRPL',
    equipment: 'Motor Gasoline MG 91',
    date: '—',
    size: '27 KB',
    revision: '',
    uploadedBy: 'MRPL',
    tags: ['Spec Sheet', 'Gasoline', 'MG 91', 'MRPL'],
    pageCount: 2,
    sourceOrg: 'Mangalore Refinery and Petrochemicals Ltd',
    sourceUrl: 'https://mrpl.co.in/sites/default/files/motor_gas_bs4_1437546019.pdf',
    authenticity: 'company',
  },
  {
    id: 'DOC-011',
    corpusId: 'DOC-011',
    name: 'DOC-011.pdf',
    subtitle: 'IOCL HSD Specification IS 1460:2017 (BS-IV and BS-VI)',
    type: 'Spec Sheet',
    typeColor: 'blue',
    iconColor: 'blue',
    unit: 'Fuels Blending',
    area: 'IOCL',
    equipment: 'HSD BS-IV/VI',
    date: '2017',
    size: '713 KB',
    revision: '',
    uploadedBy: 'IOCL',
    tags: ['Spec Sheet', 'Diesel', 'IOCL'],
    pageCount: 2,
    sourceOrg: 'Indian Oil Corporation Ltd',
    sourceUrl: 'https://iocl.com/Contents/Upload/HSD-BS-IVand-BS-VI.pdf',
    authenticity: 'company',
    viewerNote: 'Scanned image-only PDF; OCR is pending, so no text preview is available.',
  },
  {
    id: 'DOC-012',
    corpusId: 'DOC-012',
    name: 'DOC-012.pdf',
    subtitle: 'Industrial Instrumentation Ch.7: PFD/P&ID/loop/symbols/tags (TRAINING)',
    type: 'P&ID',
    typeColor: 'purple',
    iconColor: 'purple',
    unit: 'Reference Library',
    area: 'Training',
    equipment: 'P&ID Symbols & Loops',
    date: '2019-01-04',
    size: '62.1 MB',
    revision: '2.32',
    uploadedBy: 'Kuphaldt / ibiblio (OER)',
    tags: ['P&ID', 'Training', 'Symbols', 'Reference'],
    pageCount: 3311,
    sourceOrg: 'Tony R. Kuphaldt via ibiblio (OER, CC-BY-4.0)',
    sourceUrl: 'https://www.ibiblio.org/kuphaldt/socratic/sinst/book/liii_2v32.pdf',
    authenticity: 'training',
    viewerNote: 'Training reference (CC-BY-4.0) — symbols and loop diagrams, not an MRPL as-built drawing.',
  },
  {
    id: 'DOC-013',
    corpusId: 'DOC-013',
    name: 'DOC-013.pdf',
    subtitle: 'Energy Efficiency Improvement in the Petroleum Refining Industry',
    type: 'Reference',
    typeColor: 'gray',
    iconColor: 'teal',
    unit: 'Refinery-wide',
    area: 'Energy',
    equipment: 'Process Units',
    date: '2006-04-04',
    size: '175 KB',
    revision: '',
    uploadedBy: 'U.S. DOE / OSTI',
    tags: ['Reference', 'Energy', 'DOE'],
    pageCount: 13,
    sourceOrg: 'U.S. DOE / OSTI',
    sourceUrl: 'https://www.osti.gov/servlets/purl/919492',
    authenticity: 'government',
  },
]
