/**
 * Mock data for HYPERION Screen 3 — Equipment Workspace.
 * Models real MRPL Refinery operational equipment specifications,
 * hierarchy, telemetry trends, engineering documentation, and activity log.
 * @module @deepseek-ai/dsh-client-ui-conversation/client/equipment/mockData
 */

import type { EquipmentWorkspaceData } from './types.ts'

export const DEFAULT_EQUIPMENT_DATA: EquipmentWorkspaceData = {
  breadcrumb: ['Plant', 'Equipment'],
  title: 'Equipment',
  subtitle: 'Browse and explore all plant equipment  •  MRPL Refinery',

  units: [
    {
      id: 'cdu',
      code: 'CDU',
      name: 'CDU - Crude Distillation Unit',
      count: 42,
      color: 'blue',
      categories: [
        { id: 'pumps', name: 'Pumps', count: 12 },
        { id: 'exchangers', name: 'Heat Exchangers', count: 10 },
        { id: 'valves', name: 'Valves', count: 14 },
        { id: 'columns', name: 'Columns', count: 3 },
        { id: 'drums', name: 'Drums', count: 3 },
        { id: 'furnaces', name: 'Furnaces', count: 2 },
        { id: 'others', name: 'Others', count: 8 },
      ],
    },
    {
      id: 'vdu',
      code: 'VDU',
      name: 'VDU - Vacuum Distillation Unit',
      count: 28,
      color: 'blue',
      categories: [
        { id: 'vdu-pumps', name: 'Pumps', count: 8 },
        { id: 'vdu-exchangers', name: 'Heat Exchangers', count: 6 },
        { id: 'vdu-valves', name: 'Valves', count: 8 },
        { id: 'vdu-columns', name: 'Columns', count: 2 },
        { id: 'vdu-drums', name: 'Drums', count: 2 },
        { id: 'vdu-furnaces', name: 'Furnaces', count: 2 },
      ],
    },
    {
      id: 'hcu',
      code: 'HCU',
      name: 'HCU - Hydrocracking Unit',
      count: 36,
      color: 'green',
      categories: [
        { id: 'hcu-reactors', name: 'Reactors', count: 4 },
        { id: 'hcu-compressors', name: 'Compressors', count: 6 },
        { id: 'hcu-pumps', name: 'Pumps', count: 10 },
        { id: 'hcu-exchangers', name: 'Heat Exchangers', count: 8 },
        { id: 'hcu-separators', name: 'Separators', count: 4 },
        { id: 'hcu-valves', name: 'Valves', count: 4 },
      ],
    },
    {
      id: 'hdt',
      code: 'HDT',
      name: 'HDT - Hydrotreating Unit',
      count: 26,
      color: 'purple',
      categories: [
        { id: 'hdt-reactors', name: 'Reactors', count: 2 },
        { id: 'hdt-compressors', name: 'Compressors', count: 4 },
        { id: 'hdt-pumps', name: 'Pumps', count: 8 },
        { id: 'hdt-exchangers', name: 'Heat Exchangers', count: 6 },
        { id: 'hdt-columns', name: 'Columns', count: 2 },
        { id: 'hdt-vessels', name: 'Vessels', count: 4 },
      ],
    },
    {
      id: 'sru',
      code: 'SRU',
      name: 'SRU - Sulfur Recovery Unit',
      count: 18,
      color: 'amber',
      categories: [
        { id: 'sru-thermal', name: 'Thermal Reactors', count: 2 },
        { id: 'sru-catalytic', name: 'Catalytic Converters', count: 4 },
        { id: 'sru-condensers', name: 'Condensers', count: 4 },
        { id: 'sru-incinerators', name: 'Incinerators', count: 2 },
        { id: 'sru-pumps', name: 'Pumps', count: 6 },
      ],
    },
    {
      id: 'utilities',
      code: 'Utilities',
      name: 'Utilities',
      count: 98,
      color: 'cyan',
      categories: [
        { id: 'util-boilers', name: 'Boilers', count: 6 },
        { id: 'util-turbines', name: 'Steam Turbines', count: 8 },
        { id: 'util-cooling', name: 'Cooling Towers', count: 12 },
        { id: 'util-pumps', name: 'Water Treatment Pumps', count: 32 },
        { id: 'util-compressors', name: 'Air Compressors', count: 16 },
        { id: 'util-power', name: 'Power Distribution', count: 24 },
      ],
    },
    {
      id: 'offsites',
      code: 'Offsites',
      name: 'Offsites',
      count: 22,
      color: 'slate',
      categories: [
        { id: 'off-tanks', name: 'Storage Tanks', count: 12 },
        { id: 'off-pumps', name: 'Blending Pumps', count: 6 },
        { id: 'off-flares', name: 'Flares', count: 4 },
      ],
    },
  ],

  selectedUnitId: 'cdu',
  selectedCategoryId: 'pumps',

  selectedEquipment: {
    tag: 'P-101 A/B',
    name: 'Crude Feed Pump',
    service: 'Crude Feed',
    unit: 'CDU-03',
    area: '100 - Crude Preheat',
    pid: 'CDU-03-001',
    type: 'Centrifugal Pump',
    manufacturer: 'KSB',
    model: 'ETN 150-400',
    installationDate: '12 Mar 2018',
    status: 'in-service',
    statusLabel: 'In Service',
    criticality: 'high',
    criticalityLabel: 'High',
    lastMaintenance: '04 Jan 2024',
    nextMaintenance: '04 Jul 2024',
    imageUrl: '/equipment-pump.png',
    activeTab: 'overview',
    mediaMode: '3d',
  },

  performanceRange: 'Last 30 days',
  performanceMetrics: [
    {
      id: 'suction-pressure',
      name: 'Suction Pressure',
      value: '3.2 bar',
      iconKind: 'pressure-in',
      tone: 'blue',
      sparkline: [55, 52, 60, 58, 68, 65, 72, 70],
    },
    {
      id: 'discharge-pressure',
      name: 'Discharge Pressure',
      value: '28.5 bar',
      iconKind: 'pressure-out',
      tone: 'green',
      sparkline: [50, 58, 52, 65, 60, 70, 66, 68],
    },
    {
      id: 'flow-rate',
      name: 'Flow Rate',
      value: '520 m³/h',
      iconKind: 'flow',
      tone: 'purple',
      sparkline: [48, 55, 50, 62, 58, 68, 65, 72],
    },
    {
      id: 'motor-current',
      name: 'Motor Current',
      value: '68 A',
      iconKind: 'current',
      tone: 'amber',
      sparkline: [52, 50, 58, 55, 63, 60, 66, 64],
    },
    {
      id: 'vibration-rms',
      name: 'Vibration (RMS)',
      value: '2.1 mm/s',
      iconKind: 'vibration',
      tone: 'red',
      sparkline: [45, 52, 48, 60, 56, 66, 62, 65],
    },
  ],

  connectedDocuments: [
    {
      id: 'doc-1',
      name: 'P-101 Datasheet.pdf',
      type: 'Datasheet',
      date: '12 Jan 2024',
      iconColor: 'red',
    },
    {
      id: 'doc-2',
      name: 'P-101 Maintenance Manual.pdf',
      type: 'Manual',
      date: '08 Feb 2024',
      iconColor: 'purple',
    },
    {
      id: 'doc-3',
      name: 'Crude Pump Procedure.pdf',
      type: 'Procedure',
      date: '21 Mar 2024',
      iconColor: 'blue',
    },
    {
      id: 'doc-4',
      name: 'Vibration Report.pdf',
      type: 'Inspection',
      date: '04 Apr 2024',
      iconColor: 'orange',
    },
    {
      id: 'doc-5',
      name: 'Spare Parts List.pdf',
      type: 'Spare Parts',
      date: '18 May 2024',
      iconColor: 'amber',
    },
  ],
  totalDocumentsCount: 8,

  recentActivity: [
    {
      id: 'act-1',
      title: 'Vibration analysis completed',
      description: 'AI analysis report generated',
      timestamp: '2 hours ago',
      iconTone: 'green',
      iconKind: 'analysis',
    },
    {
      id: 'act-2',
      title: 'Maintenance work order closed',
      description: 'WO-2024-056',
      timestamp: '1 day ago',
      iconTone: 'amber',
      iconKind: 'workorder',
    },
    {
      id: 'act-3',
      title: 'Performance review',
      description: 'Flow rate within normal range',
      timestamp: '3 days ago',
      iconTone: 'blue',
      iconKind: 'review',
    },
    {
      id: 'act-4',
      title: 'Inspection report added',
      description: 'P-101_Vibration_Q1.pdf',
      timestamp: '5 days ago',
      iconTone: 'indigo',
      iconKind: 'report',
    },
    {
      id: 'act-5',
      title: 'Equipment created',
      description: 'Added from P&ID CDU-03-001',
      timestamp: '2 months ago',
      iconTone: 'purple',
      iconKind: 'created',
    },
  ],

  promptSuggestions: [
    {
      id: 'sugg-vibration',
      text: 'Why is vibration high recently?',
      iconType: 'sparkle',
    },
    {
      id: 'sugg-maintenance',
      text: 'Show maintenance history',
      iconType: 'sparkle',
    },
    {
      id: 'sugg-documents',
      text: 'Find related documents',
      iconType: 'document',
    },
    {
      id: 'sugg-compare',
      text: 'Compare A/B performance',
      iconType: 'compare',
    },
  ],
}
